#设置端口号
server:
  port: 8889

#给项目取名字
spring:
  profiles:
    active: dev
  application:
    name: panda-users
  #数据库连接源
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    #json对属性值为null 忽略
    default-property-inclusion: NON_NULL
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: tiger
    url: jdbc:oracle:thin:@10.1.11.252:1521:orcl
    druid:
      initSize: 5
      maxSize: 100
      minSize: 10
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  #配置连接超时时间
  mvc:
    async:
      request-timeout: 100000ms
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100000ms
    database: 0


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml


#配置主机名
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: pandaUsers:${spring.cloud.client.ipaddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka/

ribbon:
  eureka:
    enable: true

#启动pagehelper插件配置的数据库
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: countSql