#设置端口号
server:
  port: 8888


#给项目取名字
spring:
  application:
    name: panda-html
  mvc:
    async:
      request-timeout: 20000
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000

#配置主机名
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: pandaHtml:${spring.cloud.client.ipaddress}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka/

ribbon:
  eureka:
    enable: true

