#给项目取名字
spring:
  mvc:
    async:
      request-timeout: 200000
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 20000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

ribbon:
  eureka:
    enable: true
  ReadTimeout: 300000
  SocketTimeout: 300000
  ConnectTimeout: 30000

feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000

