server:
  port: 8866

spring:
  application:
    name: panda-configserver
  profiles:
    active: native  #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
  cloud:
    config:
      server:
        #如下是本地文件配置
        native:
          search-locations: classpath:/config/ #配置文件存放的目录

#eureka相关配置
eureka:
  instance:
    hostname: 127.0.0.1
    #修改eureka-client在注册中心页面显示的名字
    #${spring.cloud.client.ipaddress} 获取服务的ip地址
    instance-id: pandaConfigServer-${spring.cloud.client.ipaddress}:${server.port}
    #服务信息显示的真实的ip, 开发中一定要设置为true, 如果不设置, 其他电脑访问不到你的服务
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:11111/eureka/